services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  productservice:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: productservice
    ports:
      - "7002:8080"

  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: orderservice
    ports:
      - "7001:8080"
    depends_on:
      - rabbitmq
      - productservice

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: apigateway
    ports:
      - "7000:8080"
    depends_on:
      - productservice
      - orderservice

  notificationservice:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    container_name: notificationservice
    depends_on:
      - rabbitmq

  inventoryservice:
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    container_name: inventoryservice
    depends_on:
      - rabbitmq